# Generated by Django 5.0.6 on 2024-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_customuser_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=9, unique=True)),
                ('expected_players_count', models.IntegerField()),
                ('current_players_count', models.IntegerField()),
                ('is_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
